[project]
name = "manim-for-school"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "manim>=0.19.1",
    "manim-devanagari>=0.2.2",
    "manimpango>=0.6.1",
    "numpy>=2.3.5",
    "scipy>=1.16.3",
]
